version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    parallelism: 3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install git+https://github.com/circleci/pytest-circleci-coverage.git
      - run:
          name: Run smarter tests
          command: 
            mkdir -p test-results
            circleci run testsuite "flask smarter tests" --verbose
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  repro:
    jobs:
      - test
